import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const kycStepStyles = StyleSheet.create({
  modalLabel: { marginBottom: 8 },
  dropdown: { marginBottom: 0 },
  idTypeRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 10, gap: 10 },
  idTypeBtn: { flex: 1, padding: 14, borderRadius: 10, borderWidth: 1, alignItems: "center" },
  idTypeSelected: { borderColor: colors.buttonBg || "#FFA500", borderWidth: 1 },
  idTypeCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  idTypeCardSelected: { borderWidth: 1 },
  idTypeRadioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  idTypeRadioInner: { width: 10, height: 10, borderRadius: 5, borderWidth: 1, },
  idTypeLabel: { flex: 1 },
  modalInput: { borderRadius: 10, borderWidth: 1, paddingHorizontal: 14, height: 48, marginBottom: 12 },
  idCardPlaceholderIcon: { width: "100%", minHeight: 160, marginBottom: 8 },
  guidanceRow: { flexDirection: "row", gap: 8 },
  guidanceBox: { flex: 1, borderRadius: 10, alignItems: "center", justifyContent: "center", position: "relative" },
  guidanceCardImage: { width: 100, height: 120, marginBottom: 8 },
  idTypeInfoRow: { flexDirection: "row", alignItems: "center", padding: 10, borderRadius: 10 },
  uploadRow: { flexDirection: "row", gap: 12, marginTop: 12 },
  uploadBoxNew: {
    flex: 1,
    height: 130,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    paddingVertical: 12,
    position: "relative",
  },
  uploadBoxPlaceholderBg: { position: "absolute", left: 0, top: 0, width: "100%", height: "100%", opacity: 0.25 },
  uploadBoxContent: { alignItems: "center", justifyContent: "center", zIndex: 1 },
  uploadBoxIcon: { width: 30, height: 30, marginBottom: 8 },
  uploadedImg: { width: "90%", height: "100%", borderRadius: 10 },
  uploadTaxBox: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginTop: 4,
  },
  taxDocCapturedWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
    paddingHorizontal: 16,
    overflow: "hidden",
  },
  taxDocPreviewWrap: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 12,
    overflow: "hidden",
    alignSelf: "center",
    backgroundColor: "transparent",
  },
  uploadTaxContent: { alignItems: "center", justifyContent: "center", paddingVertical: 16 },
  uploadTaxIcon: { width: 40, height: 40, marginBottom: 10 },
  selfieCaptureBox: {
    minHeight: 200,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  selfiePlaceholderWrap: { alignItems: "center", width: "100%" },
  selfieCirclePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(128,128,128,0.5)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 16,
  },
  selfieCircleImg: { width: 70, height: 70 },
  startCameraBtn: { paddingVertical: 8, paddingHorizontal: 24, borderRadius: 30, borderWidth: 1, alignItems: "center", flexDirection: "row", gap: 10 },
  startCameraIcon: { width: 18, height: 18 },
  selfieCapturedWrap: { alignItems: "center", width: "100%" },
  selfiePreviewBig: { width: 120, height: 120, borderRadius: 60, marginBottom: 12 },
  retakeBtn: { paddingVertical: 6 },
  faceCircle: { width: 120, height: 120, borderRadius: 60, overflow: "hidden", borderWidth: 3, borderColor: "#28a745", alignSelf: "center" },
  faceImg: { width: "100%", height: "100%" },
  successTxt: { color: "#59a781", textAlign: "center", marginVertical: 5 },
  reviewCard: { padding: 16, borderRadius: 12 },
  reviewProfileRow: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
  reviewProfileLeft: { alignItems: "center", minWidth: 88 },
  reviewAvatarCircle: { width: 80, height: 80, borderRadius: 40, overflow: "hidden", borderWidth: 2, borderColor: "#28a745" },
  reviewAvatarImg: { width: "100%", height: "100%" },
  reviewInfoList: { flex: 1, minWidth: 0 },
  reviewInfoRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  reviewInfoLabel: { minWidth: 100, flexShrink: 0 },
  reviewInfoValue: { flex: 1, marginLeft: 12, textAlign: "right" },
  reviewDocNumberCard: { flexDirection: "row", alignItems: "center", padding: 12, borderRadius: 12, marginTop: 12 },
  reviewDocGrid: { flexDirection: "row", marginTop: 12 },
  reviewDocCard: { flex: 1, minWidth: 0, marginRight: 6, padding: 12, borderRadius: 12 },
  reviewDocImgWrap: { height: 120, borderRadius: 8, overflow: "hidden", borderWidth: 1, borderColor: "rgba(128,128,128,0.3)", alignItems: "center", justifyContent: "center" },
  otpCodeLabelRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  otpCodeLabelLine: { flex: 1, height: 1 },
  otpCodeLabel: { marginHorizontal: 10 },
  otpInputRow: { flexDirection: "row", alignItems: "center", height: 48, borderRadius: 10, borderWidth: 1, paddingRight: 8, overflow: "hidden" },
  otpInputMain: { flex: 1, marginTop: 0, minWidth: 0 },
  otpInputInner: { flex: 1, marginTop: 0, marginBottom: 0, height: 46, borderWidth: 0, borderRadius: 0, backgroundColor: "transparent" },
  otpGetOtpBtn: { backgroundColor: "#FFF", paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8 },
  otpGetOtpBtnDisabled: { backgroundColor: "#E0E0E0" },
  otpSubmitBtn: { paddingVertical: 14, borderRadius: 30, alignItems: "center" },
  otpBackBtn: { backgroundColor: "#FFF", paddingVertical: 14, borderRadius: 30, alignItems: "center", borderWidth: 1, borderColor: "rgba(0,0,0,0.1)" },
  modalFooter: { flexDirection: "row", gap: 12, marginTop: 20, justifyContent: "flex-end" },
  modalBtn: { paddingVertical: 12, paddingHorizontal: 24, borderRadius: 10, alignItems: "center", minWidth: 100 },
  modalBtnSecondary: { borderWidth: 1 },
  modalBtnPrimary: { backgroundColor: colors.buttonBg || "#FFA500" },
  guidanceBadge: { position: "absolute", top: 4, right: 4 },
  guidanceBadgeIcon: { width: 16, height: 16 },
  idCardCheckBadge: { position: "absolute", bottom: 8, right: "50%", marginRight: -12 },
  idCardCheckIcon: { width: 24, height: 24 },
  otpModalCloseBtn: { width: 30, height: 30, borderRadius: 18, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },
  kycModal: { margin: 20, justifyContent: "center" },
});
