//Stacks are defined here
export const NAVIGATION_AUTH_LOADING_STACK: string =
  'NAVIGATION_AUTH_LOADING_STACK';
export const NAVIGATION_AUTH_STACK: string = 'NAVIGATION_AUTH_STACK';
export const NAVIGATION_TRADE_STACK: string = 'NAVIGATION_TRADE_STACK';
export const NAVIGATION_BOTTOM_TAB_STACK: string =
  'NAVIGATION_BOTTOM_TAB_STACK';

//Screens are defined here
export const NAVIGATION_AUTH_LOADING_SCREEN: string =
  'NAVIGATION_AUTH_LOADING_SCREEN';
export const WELCOME_SCREEN: string = 'WELCOME_SCREEN';
export const LOGIN_SCREEN: string = 'LOGIN_SCREEN';
export const REGISTER_SCREEN: string = 'REGISTER_SCREEN';
export const VERIFY_ACCOUNT_SCREEN: string = 'VERIFY_ACCOUNT_SCREEN';
export const ACCOUNT_ACTIVATED_SCREEN: string = 'ACCOUNT_ACTIVATED_SCREEN';
export const FORGOT_PASSWORD_SCREEN: string = 'FORGOT_PASSWORD_SCREEN';
export const OTP_VERIFY_SCREEN: string = 'OTP_VERIFY_SCREEN';
export const AUTH_VERIFICATION_SCREEN: string = 'AUTH_VERIFICATION_SCREEN';
export const RESET_PASSWORD_SCREEN: string = 'RESET_PASSWORD_SCREEN';
export const HOME_SCREEN: string = 'HOME_SCREEN';
export const SEARCH_SCREEN: string = 'SEARCH_SCREEN';
export const TRADE_SCREEN: string = 'TRADE_SCREEN';
export const SWAPNEXBCOIN_SCREEN: string = 'SWAPNEXBCOIN_SCREEN';
export const WALLET_SCREEN: string = 'WALLET_SCREEN';
export const FUTURES_SCREEN: string = 'FUTURES_SCREEN';
export const ACCOUNT_SCREEN: string = 'ACCOUNT_SCREEN';
export const NOTIFICATION_SCREEN: string = 'NOTIFICATION_SCREEN';
export const EDIT_PROFILE_SCREEN: string = 'EDIT_PROFILE_SCREEN';
export const NOTIFICATION_SETTINGS_SCREEN: string =
  'NOTIFICATION_SETTINGS_SCREEN';
export const SETTINGS_SCREEN: string = 'SETTINGS_SCREEN';
export const KYC_STEP_ONE_SCREEN: string = 'KYC_STEP_ONE_SCREEN';
export const KYC_STEP_TWO_SCREEN: string = 'KYC_STEP_TWO_SCREEN';
export const KYC_STEP_THREE_SCREEN: string = 'KYC_STEP_THREE_SCREEN';
export const KYC_STEP_FOUR_SCREEN: string = 'KYC_STEP_FOUR_SCREEN';
export const KYC_STEP_FIVE_SCREEN: string = 'KYC_STEP_FIVE_SCREEN';
export const KYC_STEP_SIX_SCREEN: string = 'KYC_STEP_SIX_SCREEN';
export const KYC_VERIFICATION_SCREEN: string = 'KYC_VERIFICATION_SCREEN';
export const KYC_RESUBMIT_SCREEN: string = 'KYC_RESUBMIT_SCREEN';
export const KYC_STATUS_SCREEN: string = 'KYC_STATUS_SCREEN';
export const BANKING_AND_TRADE_SETTINGS_SCREEN: string =
  'BANKING_AND_TRADE_SETTINGS_SCREEN';
export const INVITE_AND_EARN_SCREEN: string = 'INVITE_AND_EARN_SCREEN';
export const REFFERAL_TREE = "REFFERAL_TREE";
export const CONTACT_US_SCREEN: string = 'CONTACT_US_SCREEN';
export const CMS_SCREEN: string = 'CMS_SCREEN';
export const CHANGE_PASSWORD_SCREEN: string = 'CHANGE_PASSWORD_SCREEN';
export const CURRENCY_PREFERENCE_SCREEN: string = 'CURRENCY_PREFERENCE_SCREEN';
export const COIN_DETAILS_SCREEN: string = 'COIN_DETAILS_SCREEN';
export const DEPOSIT_SCREEN: string = 'DEPOSIT_SCREEN';
export const WITHDRAW_SCREEN: string = 'WITHDRAW_SCREEN';
export const CONVERT_SCREEN: string = 'CONVERT_SCREEN';
export const WALLET_DETAIL_SCREEN: string = 'WALLET_DETAIL_SCREEN';
export const DEPOSIT_INR_SCREEN: string = 'DEPOSIT_INR_SCREEN';
export const WITHDRAW_INR_SCREEN: string = 'WITHDRAW_INR_SCREEN';
export const WALLET_HISTORY_DETAILS_SCREEN: string =
  'WALLET_HISTORY_DETAILS_SCREEN';
export const TRADE_HISTORY_DETAILS_SCREEN: string =
  'TRADE_HISTORY_DETAILS_SCREEN';
export const PAYMENT_OPTIONS_SCREEN: string = 'PAYMENT_OPTIONS_SCREEN';
export const TRADE_SETTINGS_SCREEN: string = 'TRADE_SETTINGS_SCREEN';
export const FEE_SETTINGS_SCREEN: string = 'FEE_SETTINGS_SCREEN';
export const DOWNLOAD_TRADE_REPORT_SCREEN: string =
  'DOWNLOAD_TRADE_REPORT_SCREEN';
export const ADD_NEW_BANK_SCREEN: string = 'ADD_NEW_BANK_SCREEN';
export const UPDATE_KGIN_SCREEN: string = 'UPDATE_KGIN_SCREEN';
export const COIN_DETAILS_CHART_SCREEN: string = 'COIN_DETAILS_CHART_SCREEN';
export const COIN_TRANSACTION_HISTORY_SCREEN: string =
  'COIN_TRANSACTION_HISTORY_SCREEN';
export const TWO_FACTOR_AUTHENTICATION: string = 'TWO_FACTOR_AUTHENTICATION';
export const TWO_FACTOR_QR_SCREEN: string = 'TWO_FACTOR_QR_SCREEN';
export const ADD_PHONE_NUMBER_SCREEN: string = 'ADD_PHONE_NUMBER_SCREEN';
export const ADD_EMAIL_SCREEN: string = 'ADD_EMAIL_SCREEN';
export const SETUP_TWO_FACTOR_SCREEN: string = 'SETUP_TWO_FACTOR_SCREEN';
export const VERIFY_AUTHENTICATOR_CODE_SCREEN: string = 'VERIFY_AUTHENTICATOR_CODE_SCREEN';
export const ADD_PASSKEY_SCREEN: string = 'ADD_PASSKEY_SCREEN';
export const CHANGE_EMAIL_SCREEN: string = 'CHANGE_EMAIL_SCREEN';
export const CHANGE_MOBILE_SCREEN: string = 'CHANGE_MOBILE_SCREEN';
export const VIEW_PASSKEYS_SCREEN: string = 'VIEW_PASSKEYS_SCREEN';
export const DISABLE_2FA_SCREEN: string = 'DISABLE_2FA_SCREEN';
export const ENTER_OTP_SCREEN: string = 'ENTER_OTP_SCREEN';
export const CONVERT_HISTORY_SCREEN: string = 'CONVERT_HISTORY_SCREEN';
export const LANGUAGE_PREFERENCE_SCREEN: string = 'LANGUAGE_PREFERENCE_SCREEN';
export const QUICK_BUY_SELL: string = 'QUICK_BUY_SELL';
export const QS_TRANSACTION: string = 'QS_TRANSACTION';

export const STAKING: string = 'STAKING';
export const STAKING_SUCCESS: string = 'STAKING_SUCCESS';
export const LAKED_STAKING: string = 'LAKED_STAKING';
export const STAKING_HISTORY: string = 'STAKING_HISTORY';
export const p2pHome: string = 'STAKING_HISTORY';
export const p2pOrder: string = 'p2pOrder';
export const p2pProfile: string = 'p2pProfile';
export const p2pAds: string = 'p2pAds';
export const p2pFilter: string = 'p2pFilter';
export const BUY_CRYPTO: string = 'buyCrypto';
export const ORDER_CREATED: string = 'ORDER_CREATED';
export const TRADE: string = 'TRADE';
export const ORDER_HISTORY = "ORDER_HISTORY";
export const SPOT_ORDER_HISTORY_DETAIL = "SPOT_ORDER_HISTORY_DETAIL";
export const FUTURE_ORDER_HISTORY = "FUTURE_ORDER_HISTORY";
export const PROJECT_COMMIT = 'PROJECT_COMMIT';
export const COMMIT_DETAIL = "COMMIT_DETAIL";
export const ACTIVITY_LOGS = "ACTIVITY_LOGS";
export const REFERRAL_LIST= "REFERRAL_LIST";
export const WALLET_HISTORY_SCREEN = 'WALLET_HISTORY_SCREEN';
export const MARKET_SCREEN = 'MARKET_SCREEN';
export const SPOT_MARKET_SCREEN = 'SPOT_MARKET_SCREEN';
export const MORE_MENU_SCREEN = "MORE_MENU_SCREEN";
export const EARING_SCREEN = "EARING_SCREEN";
export const TRANSFER_SCREEN = "TRANSFER_SCREEN";
export const DEPOSIT_WALLET_SCREEN = "DEPOSIT_WALLET_SCREEN";
export const DEPOSIT_COIN_SCREEN = "DEPOSIT_COIN_SCREEN";
export const WALLET_WITHDRAW_SCREEN = "WALLET_WITHDRAW_SCREEN";
export const WITHDRAW_Coin_SCREEN = "WITHDRAW_Coin_SCREEN";
export const AIRDROP_SCREEN = "AIRDROP_SCREEN";
export const AIRDROP_HISTORY_SCREEN = "AIRDROP_HISTORY_SCREEN";
// export const EARING_SCREEN
export const ARBITORY_SCREEN = 'ArbitoryBot'
export const Dashboard_Inner = 'DashboardInnder'


export const kyc_Details = 'kycDetails'
export const SECURITY = "Security"
export const SETTING_SCREEN_New = 'SettingsScreen'
export const OPTIONS_SCREEN = 'OPTIONS_SCREEN'
export const BUY_OPTIONS_SCREEN = 'BUY_OPTIONS_SCREEN'
export const OPTIONS_HISTORY_SCREEN = 'OPTIONS_HISTORY_SCREEN'
export const ANTI_PHISHING_CODE_SCREEN: string = 'ANTI_PHISHING_CODE_SCREEN';



